name: Version 2

on:
  push: ['*']

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '5.0.x'

      - name: Check Version
        run: dotnet --version
